### ISSUE TITLE
set_dst_hw_params: Could not open destination device: Device or resource busy

### ISSUE THREAD

**Issue by ghost** [gimesketvirtadieni/slimplexor#1]
Hi,
Thank you for the very clear instructions. I managed to get Slimplexor working (as far as I can tell!), but  the sample file I first used didn't work.
Would you be able to point me to the right direction to fix this?

Here is a failing playback:
```
$ aplay sample.wav 
Playing WAVE 'sample.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
INFO: set_dst_hw_params: destination device=hw:2,0,1
INFO: set_dst_hw_params: destination period size=4096
INFO: set_dst_hw_params: destination periods=8
ERROR: set_dst_hw_params: Could not open destination device: Device or resource busy
aplay: set_params:1363: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 44100
PERIOD_TIME: (92879 92880)
PERIOD_SIZE: 4096
PERIOD_BYTES: 16384
PERIODS: 8
BUFFER_TIME: (743038 743039)
BUFFER_SIZE: 32768
BUFFER_BYTES: 131072
TICK_TIME: [0 0]
```
I uploaded the sample.wav file I used here: https://files.fm/u/mjkxekn2#/

For info, I am running the latest version of OSMC (Debian Stretch) on a Raspberry 3.

**Comment by gimesketvirtadieni** [comment]
Hello Ronan

Indeed, it looks like you managed to set up SlimPlexor as required, congrats! The problem you are facing is not with SlimPlexor. It gets an 'open' signal from aplay'er with data about sampling rate. Based on that it looks up a destination device for this sampling rate (44100 maps to hw:2,0,1) and tries to open it. Unfortunately some other application opened hw:2,0,1 device before so ALSA rejects a request from SlimPlexor. Please try running 'fuser -fv /dev/snd/*' command so figure out which process uses this device. Loopback devices hw:2,* are meant to pass PCM from SlimPlexor to SlimStreamer, so no other software should use them ;)
