### ISSUE TITLE
Device selection

### ISSUE THREAD

**Issue by hd-info** [gimesketvirtadieni/slimplexor#3]
I managed to get it all working without problems. aplay somewavfile.wav plays and even squeezelite on another machine plays via slimstreamer.
My problem is that in my application I do not use 'default' alsa card. I use hw:x,y addressing (because my application allows users to select the card they wish to play to)
I see that aplay selects hw:2,0,1 but I don't understand why exactly this one and will it always work on this one?
I cannot try to select hw:2,0,1 in my app because at the moment it does not support subdevices but I'm also not sure it will work even if I provide that.
I tried with `aplay -D hw:2,0,1` but then it complains about format and I cannot seem to guess the correct format it would accept.
I tried with `aplay -f S32_LE -D hw:2,0,1` because that is the format ALSA told me was available but it didn't work: 
`aplay: set_params:1339: Sample format non available`

The main question is: why exactly hw:2,0,1? There are 2 cards each with 2 devices each with 8 subdevices. Also, why not hw:2,0,0? If it would be possible to make it work for hw:2,0,0 then I would not need subdevices and I could address it with just hw:2,0.

I obviously don't grasp what's beneath snd_aloop and why slimstreamer needs 8 subdevices (I tried with lower than 8 and slimstreamer complained). Can you explain all this a little or just point to somewhere where I could learn about it (I just could not find it myself, I tried).

Another issue are large gaps (several seconds) in playback (aplay -> snd_alloop -> slimstreamer -> squeezelite) but right now only above interests me.

**Comment by gimesketvirtadieni** [comment]
Hi. Right, so you question is about about PCM stream 'path' through all those ALSA devices.
As you know, an app opens an ALSA device to write to. There are two types of devices: the ones that start with 'hw:' and the rest. So if device name does not start with 'hw:', the ALSA will use asound.conf to resolve how PCM routing is done (actually it is way more complicated but it is good enough for a mental model). If device name starts with 'hw:' then ALSA does not do any 'routing' - it sends provided PCM stream straight to that device. In such a case (when asound.conf is not involved) it is not possible to 'high-jack' the stream (at least to my knowledge). So if you want to use SlimPlexos/SlimStreamer, you should always use a target device which is defined somewhere in asound.conf file (default falls into this category as well).
So let's say you use a default device and you have asound.conf defined as required for SlimStream, then what happens is SlimPlexor is loaded as ALSA plugin within the context of PCM originator's process. It receives PCM stream as originator wrote to ALSA along with metadata (like sampling rate, format, etc.). What it does is it resends PCM to one of hw:1.0.X/hw:2.0.X; specific device is selected based on sampling rate (one device per sampling rate). The thing is that ALSA has a limitation on amount of subdevices so I had to use two devices (hw:1.0 and hw:2.0). Also SlimPlexor adds an extra channel while forwarding which contains encoded meta data for each frame.
Why is this forwarding needed? The thing is SlimPlexor runs within a context of the originator's process (let's say aplay), whereas SlimStreamer is a separate process which has to receive that stream to be able to send it out. That is why ALSA loopback is used - whatever was sent by SlimPlexor to hw:1.0.1 is available for SlimStreamer on hw:1.1.1 device. Think of loopback devices as of very special IPC with 'nice' properties.
Now comming back to your application (or aplay), SlimStreamer is based on an idea that there is a virtual ALSA device so if any app plays to that device - audio is streamed to all current players. Now if app plays to hw:0.X then it is not the case any more. So please consider using a dedicated ALSA device defined in asound.conf meant for streaming. Also please review a drawing available on SlimStreamer page. And do let me know if you have further questions ;)

**Comment by hd-info** [comment]
Thank you for these detailed explanations.
I see that I cannot use hw: to achieve anything with Plexor.
As for device selection If I understood correctly, every subdevice accepts one predefined sampling rate and subdevice selection is based then on source stream samplerate?  And you needed more than 8 to cover all samplerates.
Ok, thanks  again.

**Comment by gimesketvirtadieni** [comment]
Hi. Exactly, subdevice selection is based on originated sampling rate (sampling rate chosen by a client app, for example aplay). The thing is SlimStreamer reads from ALL those subdevices simultaneously and picks the one which actually contains PCM data for streaming (hence the naming (de)multiplexing). Such design allows reliable and timely detection when client switches to a different rate. It also allows to avoid resampling done by other solutions.
Feel free to reopen this issue if you have further questions ;)

**Comment by hd-info** [comment]
Sorry, one more question. 
You said 'it resends PCM to one of hw:1.0.X/hw:2.0.X'
In my system snd_aloop output is always hw:2.0.X. 
In addressing, I must know to send to either sysdefault:CARD=Loopback2 or sysdefault:CARD=Loopback1
Your wording sound like it may not always be the case?

**Comment by gimesketvirtadieni** [comment]
Hi. I suppose you always see destination devices as hw:2.0.X due to used sampling rates, which in your case are >= 44100. Please check pcm_slimplexor.c file in this repo which contains the actual mapping (rate<->device). You can just grep for rate_device_map in that file. Currently this mapping is hardcoded.
